name: Update data

on:
  schedule:
    - cron: "40 * * * *"
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update data
      run: ./update.sh
    - name: Build
      uses: actions/setup-node@v1
      run: >
        npm i
        npm run build
        cp CNAME public/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public/
